# Generated by Django 2.0.7 on 2018-07-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_auto_20180725_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.CharField(default='New entry', max_length=80),
        ),
    ]
