# Generated by Django 2.0.7 on 2018-07-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_entry_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(default=None, max_length=80),
        ),
    ]
